{
  "Aluminium foil": "metal",
  "Battery": "metal",
  "Aluminium blister pack": "metal",
  "Carded blister pack": "plastic",
  "Other plastic bottle": "plastic",
  "Plastic drink bottle": "plastic",
  "Glass bottle": "glass",
  "Plastic bottle cap": "plastic",
  "Metal bottle cap": "metal",
  "Broken glass": "glass",
  "Food Can": "metal",
  "Aerosol": "metal",
  "Drink can": "metal",
  "Toilet tube": "plastic",
  "Other carton": "paper",
  "Egg carton": "paper",
  "Drink carton": "paper",
  "Corrugated carton": "paper",
  "Meal carton": "paper",
  "Pizza box": "paper",
  "Paper cup": "paper",
  "Disposable plastic cup": "plastic",
  "Foam cup": "plastic",
  "Glass cup": "glass",
  "Other plastic cup": "plastic",
  "Food waste": "organic",
  "Glass jar": "glass",
  "Plastic lid": "plastic",
  "Metal lid": "metal",
  "Other plastic": "plastic",
  "Magazine paper": "paper",
  "Tissues": "paper",
  "Wrapping paper": "paper",
  "Normal paper": "paper",
  "Paper bag": "paper",
  "Plastified paper bag": "paper",
  "Plastic Film": "plastic",
  "Six pack rings": "plastic",
  "Garbage bag": "plastic",
  "Other plastic wrapper": "plastic",
  "Single-use carrier bag": "plastic",
  "Polypropylene bag": "plastic",
  "Crisp packet": "plastic",
  "Spread tub": "plastic",
  "Tupperware": "plastic",
  "Disposable food container": "plastic",
  "Foam food container": "plastic",
  "Other plastic container": "plastic",
  "Plastic glooves": "plastic",
  "Plastic utensils": "plastic",
  "Pop tab": "metal",
  "Rope & strings": "other",
  "Scrap metal": "metal",
  "Shoe": "other",
  "Squeezable tube": "plastic",
  "Plastic straw": "plastic",
  "Paper straw": "paper",
  "Styrofoam piece": "plastic",
  "Unlabeled litter": "other",
  "Cigarette": "organic"
}
